-- models/silver/basic_financials_metrics.sql
-- Flat scalar metrics from the metric block
-- One row per ticker per pull date
SELECT
    ticker,
    pulled_at,
    data:metric:tenDayAverageTradingVolume::FLOAT       AS ten_day_avg_trading_volume,
    data:metric:thirteenWeekPriceReturnDaily::FLOAT     AS thirteen_week_price_return_daily,
    data:metric:twentySixWeekPriceReturnDaily::FLOAT    AS twenty_six_week_price_return_daily,
    data:metric:fiftyTwoWeekHigh::FLOAT                 AS fifty_two_week_high,
    data:metric:fiftyTwoWeekHighDate::VARCHAR           AS fifty_two_week_high_date,
    data:metric:fiftyTwoWeekLow::FLOAT                  AS fifty_two_week_low,
    data:metric:fiftyTwoWeekLowDate::VARCHAR            AS fifty_two_week_low_date,
    data:metric:fiftyTwoWeekPriceReturnDaily::FLOAT     AS fifty_two_week_price_return_daily,
    data:metric:beta::FLOAT                             AS beta,
    data:metric:marketCapitalization::FLOAT             AS market_capitalization,
    data:metric:enterpriseValue::FLOAT                  AS enterprise_value,
    data:metric:forwardPE::FLOAT                        AS forward_pe,
    data:metric:peAnnual::FLOAT                         AS pe_annual,
    data:metric:peTTM::FLOAT                            AS pe_ttm,
    data:metric:pbAnnual::FLOAT                         AS pb_annual,
    data:metric:psAnnual::FLOAT                         AS ps_annual,
    data:metric:psTTM::FLOAT                            AS ps_ttm,
    data:metric:epsAnnual::FLOAT                        AS eps_annual,
    data:metric:epsTTM::FLOAT                           AS eps_ttm,
    data:metric:epsGrowth3Y::FLOAT                      AS eps_growth_3y,
    data:metric:epsGrowth5Y::FLOAT                      AS eps_growth_5y,
    data:metric:grossMarginAnnual::FLOAT                AS gross_margin_annual,
    data:metric:grossMarginTTM::FLOAT                   AS gross_margin_ttm,
    data:metric:grossMargin5Y::FLOAT                    AS gross_margin_5y,
    data:metric:netProfitMarginAnnual::FLOAT            AS net_profit_margin_annual,
    data:metric:netProfitMarginTTM::FLOAT               AS net_profit_margin_ttm,
    data:metric:netProfitMargin5Y::FLOAT                AS net_profit_margin_5y,
    data:metric:operatingMarginAnnual::FLOAT            AS operating_margin_annual,
    data:metric:operatingMarginTTM::FLOAT               AS operating_margin_ttm,
    data:metric:operatingMargin5Y::FLOAT                AS operating_margin_5y,
    data:metric:roaAnnual::FLOAT                        AS roa_annual,
    data:metric:roaRfy::FLOAT                           AS roa_rfy,
    data:metric:roaTTM::FLOAT                           AS roa_ttm,
    data:metric:roa5Y::FLOAT                            AS roa_5y,
    data:metric:roeTTM::FLOAT                           AS roe_ttm,
    data:metric:roeRfy::FLOAT                           AS roe_rfy,
    data:metric:roe5Y::FLOAT                            AS roe_5y,
    data:metric:roiAnnual::FLOAT                        AS roi_annual,
    data:metric:roiTTM::FLOAT                           AS roi_ttm,
    data:metric:roi5Y::FLOAT                            AS roi_5y,
    data:metric:revenueGrowth3Y::FLOAT                  AS revenue_growth_3y,
    data:metric:revenueGrowth5Y::FLOAT                  AS revenue_growth_5y,
    data:metric:revenueGrowthTTMYoy::FLOAT              AS revenue_growth_ttm_yoy,
    data:metric:assetTurnoverAnnual::FLOAT              AS asset_turnover_annual,
    data:metric:assetTurnoverTTM::FLOAT                 AS asset_turnover_ttm,
    data:metric:currentRatioAnnual::FLOAT               AS current_ratio_annual,
    data:metric:currentRatioQuarterly::FLOAT            AS current_ratio_quarterly,
    data:metric:quickRatioAnnual::FLOAT                 AS quick_ratio_annual,
    data:metric:quickRatioQuarterly::FLOAT              AS quick_ratio_quarterly,
    data:metric:dividendYieldIndicatedAnnual::FLOAT     AS dividend_yield_indicated_annual,
    data:metric:dividendPerShareAnnual::FLOAT           AS dividend_per_share_annual,
    data:metric:dividendGrowthRate5Y::FLOAT             AS dividend_growth_rate_5y,
    data:metric:payoutRatioAnnual::FLOAT                AS payout_ratio_annual,
    data:metric:payoutRatioTTM::FLOAT                   AS payout_ratio_ttm,
    data:metric:longTermDebt_equityAnnual::FLOAT        AS long_term_debt_equity_annual,
    data:metric:totalDebt_totalEquityAnnual::FLOAT      AS total_debt_equity_annual,
    data:metric:inventoryTurnoverAnnual::FLOAT          AS inventory_turnover_annual,
    data:metric:inventoryTurnoverTTM::FLOAT             AS inventory_turnover_ttm,
    data:metric:receivablesTurnoverAnnual::FLOAT        AS receivables_turnover_annual,
    data:metric:receivablesTurnoverTTM::FLOAT           AS receivables_turnover_ttm
FROM FINNHUB.FINNHUB_BRONZE.basic_financials_raw