-- models/silver/usa_spending.sql
-- GOOD
SELECT
    ticker,
    pulled_at,
    value:actionDate::VARCHAR                          AS action_date,
    value:awardDescription::VARCHAR                    AS award_description,
    value:awardingAgencyName::VARCHAR                  AS awarding_agency_name,
    value:awardingOfficeName::VARCHAR                  AS awarding_office_name,
    value:awardingSubAgencyName::VARCHAR               AS awarding_sub_agency_name,
    value:country::VARCHAR                             AS country,
    value:lastModifiedDate::VARCHAR                    AS last_modified_date,
    value:naicsCode::VARCHAR                           AS naics_code,
    value:obligatedAmount::INTEGER                     AS obligated_amount,
    value:outlayedAmount::INTEGER                      AS outlayed_amount,
    value:performanceCity::VARCHAR                     AS performance_city,
    value:performanceCongressionalDistrict::VARCHAR    AS performance_congressional_district,
    value:performanceCountry::VARCHAR                  AS performance_country,
    value:performanceCounty::VARCHAR                   AS performance_county,
    value:performanceEndDate::VARCHAR                  AS performance_end_date,
    value:performanceStartDate::VARCHAR                AS performance_start_date,
    value:performanceState::VARCHAR                    AS performance_state,
    value:performanceZipCode::VARCHAR                  AS performance_zip_code,
    value:permalink::VARCHAR                           AS permalink,
    value:potentialAmount::NUMBER(20,0)                AS potential_amount,
    value:recipientName::VARCHAR                       AS recipient_name,
    value:recipientParentName::VARCHAR                 AS recipient_parent_name,
    data:symbol::VARCHAR                               AS symbol,
    value:totalValue::INTEGER                          AS total_value
FROM FINNHUB.FINNHUB_BRONZE.usa_spending_raw,
LATERAL FLATTEN(input => data:data)